/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package demo

import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class AppTest extends AnyFunSuite {
  test("App has a greeting") {
//    fail()
    assert(App.greeting() != null)
  }
}
