/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package demo

import org.junit.runner.RunWith
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.must.Matchers._
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class ByteReaderTest extends AnyFlatSpec {
  "ByteReader1" should "read [31,32,33] from bytes.txt" in {
    val reader: ByteReader = new ByteReaderImpl("src/test/resources/bytes.txt")
    var res = List.empty[Int];
    reader.readFile(
      c => res = c :: res
    )
    res.reverse must contain theSameElementsInOrderAs List(0x31, 0x32, 0x33)
  }
}
